//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.CalculateReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculateReference.CalculateSoap")]
    public interface CalculateSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DemoApp.CalculateReference.HelloWorldResponse HelloWorld(DemoApp.CalculateReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.HelloWorldResponse> HelloWorldAsync(DemoApp.CalculateReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXML", ReplyAction="*")]
        int AddXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXML", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXMLWithParameters", ReplyAction="*")]
        int AddXMLWithParameters(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXMLWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddXMLWithParametersAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXMLWithParameters2", ReplyAction="*")]
        int AddXMLWithParameters2(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddXMLWithParameters2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddXMLWithParameters2Async(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWithJSON", ReplyAction="*")]
        int AddWithJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWithJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddWithJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWithJSONWithParameters", ReplyAction="*")]
        int AddWithJSONWithParameters(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWithJSONWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddWithJSONWithParametersAsync(int x, int y);
        
        // CODEGEN: Generating message contract since the wrapper name (AddTwoNumber) of message AddTwoNumber does not match the default value (AddWithSession)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumber", ReplyAction="*")]
        DemoApp.CalculateReference.AddTwoNumber1 AddWithSession(DemoApp.CalculateReference.AddTwoNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.AddTwoNumber1> AddWithSessionAsync(DemoApp.CalculateReference.AddTwoNumber request);
        
        // CODEGEN: Generating message contract since element name GetAllAddOperationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAddOperations", ReplyAction="*")]
        DemoApp.CalculateReference.GetAllAddOperationsResponse GetAllAddOperations(DemoApp.CalculateReference.GetAllAddOperationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAddOperations", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.GetAllAddOperationsResponse> GetAllAddOperationsAsync(DemoApp.CalculateReference.GetAllAddOperationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.CalculateReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DemoApp.CalculateReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.CalculateReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DemoApp.CalculateReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTwoNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddTwoNumber {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int y;
        
        public AddTwoNumber() {
        }
        
        public AddTwoNumber(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTwoNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddTwoNumber1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddTwoNumberResult;
        
        public AddTwoNumber1() {
        }
        
        public AddTwoNumber1(int AddTwoNumberResult) {
            this.AddTwoNumberResult = AddTwoNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAddOperationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAddOperations", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.CalculateReference.GetAllAddOperationsRequestBody Body;
        
        public GetAllAddOperationsRequest() {
        }
        
        public GetAllAddOperationsRequest(DemoApp.CalculateReference.GetAllAddOperationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllAddOperationsRequestBody {
        
        public GetAllAddOperationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAddOperationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAddOperationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.CalculateReference.GetAllAddOperationsResponseBody Body;
        
        public GetAllAddOperationsResponse() {
        }
        
        public GetAllAddOperationsResponse(DemoApp.CalculateReference.GetAllAddOperationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAddOperationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoApp.CalculateReference.ArrayOfString GetAllAddOperationsResult;
        
        public GetAllAddOperationsResponseBody() {
        }
        
        public GetAllAddOperationsResponseBody(DemoApp.CalculateReference.ArrayOfString GetAllAddOperationsResult) {
            this.GetAllAddOperationsResult = GetAllAddOperationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateSoapChannel : DemoApp.CalculateReference.CalculateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateSoapClient : System.ServiceModel.ClientBase<DemoApp.CalculateReference.CalculateSoap>, DemoApp.CalculateReference.CalculateSoap {
        
        public CalculateSoapClient() {
        }
        
        public CalculateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoApp.CalculateReference.HelloWorldResponse DemoApp.CalculateReference.CalculateSoap.HelloWorld(DemoApp.CalculateReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DemoApp.CalculateReference.HelloWorldRequest inValue = new DemoApp.CalculateReference.HelloWorldRequest();
            inValue.Body = new DemoApp.CalculateReference.HelloWorldRequestBody();
            DemoApp.CalculateReference.HelloWorldResponse retVal = ((DemoApp.CalculateReference.CalculateSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.HelloWorldResponse> DemoApp.CalculateReference.CalculateSoap.HelloWorldAsync(DemoApp.CalculateReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoApp.CalculateReference.HelloWorldResponse> HelloWorldAsync() {
            DemoApp.CalculateReference.HelloWorldRequest inValue = new DemoApp.CalculateReference.HelloWorldRequest();
            inValue.Body = new DemoApp.CalculateReference.HelloWorldRequestBody();
            return ((DemoApp.CalculateReference.CalculateSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add() {
            return base.Channel.Add();
        }
        
        public System.Threading.Tasks.Task<int> AddAsync() {
            return base.Channel.AddAsync();
        }
        
        public int AddXML() {
            return base.Channel.AddXML();
        }
        
        public System.Threading.Tasks.Task<int> AddXMLAsync() {
            return base.Channel.AddXMLAsync();
        }
        
        public int AddXMLWithParameters(int x, int y) {
            return base.Channel.AddXMLWithParameters(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddXMLWithParametersAsync(int x, int y) {
            return base.Channel.AddXMLWithParametersAsync(x, y);
        }
        
        public int AddXMLWithParameters2(int x, int y) {
            return base.Channel.AddXMLWithParameters2(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddXMLWithParameters2Async(int x, int y) {
            return base.Channel.AddXMLWithParameters2Async(x, y);
        }
        
        public int AddWithJSON() {
            return base.Channel.AddWithJSON();
        }
        
        public System.Threading.Tasks.Task<int> AddWithJSONAsync() {
            return base.Channel.AddWithJSONAsync();
        }
        
        public int AddWithJSONWithParameters(int x, int y) {
            return base.Channel.AddWithJSONWithParameters(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddWithJSONWithParametersAsync(int x, int y) {
            return base.Channel.AddWithJSONWithParametersAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoApp.CalculateReference.AddTwoNumber1 DemoApp.CalculateReference.CalculateSoap.AddWithSession(DemoApp.CalculateReference.AddTwoNumber request) {
            return base.Channel.AddWithSession(request);
        }
        
        public int AddWithSession(int x, int y) {
            DemoApp.CalculateReference.AddTwoNumber inValue = new DemoApp.CalculateReference.AddTwoNumber();
            inValue.x = x;
            inValue.y = y;
            DemoApp.CalculateReference.AddTwoNumber1 retVal = ((DemoApp.CalculateReference.CalculateSoap)(this)).AddWithSession(inValue);
            return retVal.AddTwoNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.AddTwoNumber1> DemoApp.CalculateReference.CalculateSoap.AddWithSessionAsync(DemoApp.CalculateReference.AddTwoNumber request) {
            return base.Channel.AddWithSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoApp.CalculateReference.AddTwoNumber1> AddWithSessionAsync(int x, int y) {
            DemoApp.CalculateReference.AddTwoNumber inValue = new DemoApp.CalculateReference.AddTwoNumber();
            inValue.x = x;
            inValue.y = y;
            return ((DemoApp.CalculateReference.CalculateSoap)(this)).AddWithSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoApp.CalculateReference.GetAllAddOperationsResponse DemoApp.CalculateReference.CalculateSoap.GetAllAddOperations(DemoApp.CalculateReference.GetAllAddOperationsRequest request) {
            return base.Channel.GetAllAddOperations(request);
        }
        
        public DemoApp.CalculateReference.ArrayOfString GetAllAddOperations() {
            DemoApp.CalculateReference.GetAllAddOperationsRequest inValue = new DemoApp.CalculateReference.GetAllAddOperationsRequest();
            inValue.Body = new DemoApp.CalculateReference.GetAllAddOperationsRequestBody();
            DemoApp.CalculateReference.GetAllAddOperationsResponse retVal = ((DemoApp.CalculateReference.CalculateSoap)(this)).GetAllAddOperations(inValue);
            return retVal.Body.GetAllAddOperationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoApp.CalculateReference.GetAllAddOperationsResponse> DemoApp.CalculateReference.CalculateSoap.GetAllAddOperationsAsync(DemoApp.CalculateReference.GetAllAddOperationsRequest request) {
            return base.Channel.GetAllAddOperationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoApp.CalculateReference.GetAllAddOperationsResponse> GetAllAddOperationsAsync() {
            DemoApp.CalculateReference.GetAllAddOperationsRequest inValue = new DemoApp.CalculateReference.GetAllAddOperationsRequest();
            inValue.Body = new DemoApp.CalculateReference.GetAllAddOperationsRequestBody();
            return ((DemoApp.CalculateReference.CalculateSoap)(this)).GetAllAddOperationsAsync(inValue);
        }
    }
}
